language: python
sudo: required
matrix:
  include:
  - env: TARGET=pep8
  - env: TARGET=py2
  - env: TARGET=py3
script:
- true
install:
- docker build . -t ${TARGET} -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: athanaseus
  password:
    secure: buqYhiyyfgouESxIq29x0Z7hJQzz06y/6opPoqF7F8j+RlccpCUz5FgwkS6d15ymZDbEHsfuiuV/9HC+TVK837gPgmGZzSN4VwmKFkh+dlR3jJJSzzgniOosH1i8CqO5csi1jKxkCVD7cT+eU9VRaX3BEaKEfs1wwAvWY6Sd3G/hP705069prZ7w3EdhOLPIS6KIRVh4faFD1S1MWLEix5fFh3OtOcI5Es/5VKIG2D+QgbH4+JW7CSvs6K0Ur0M5F3R4j8BL5yOzXNtxTJDYqoDJvhMuyEb33RrSd9LYy/LwM5hSvqe5l/Xqd9EU6hARFDLTqMpi4JONqrz1oJVFx9yjszO3q1PXGD1X013j62AiOWAPfBc7RxW1JQNE3XZC/IzMA6Vk19cTJEQd4/OV86h0jHnKS2Zq+f+p0N1O6hEK2nchM1HtkGsTFjZRkyLo2PuNqz0KH6ENEf9VQxuJseDHyuWGb9PyH7SJvDMbNtLqRR5e5JFqBF7fep9xSkiNaCDoAODgNQ9ILZLfrZZUzZwaTuDy+gN3Y4oyUfFki1e21EyE73js33r1yMVv2odGm9/Qy51OM09y2ATSM9aTQPFlZ/BJL3PsWRyayWaPZCxSVdRa3Q+CnxDFGUUR99HwSDqRFJz9ReseTkoewK5Ophmm3KqO1ji/VdOFw++gxrw=
  true:
  on:
    tags: true
    distributions: sdist bdist_wheel
repo: athanaseus/Drastic
